# Generated by Django 4.1.7 on 2023-03-05 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AppBlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentario", options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.RenameField(
            model_name="comentario", old_name="fecha", new_name="fecha_creacion",
        ),
        migrations.RemoveField(model_name="comentario", name="autor",),
        migrations.AddField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="pelicula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios_pelis",
                to="AppBlog.pelicula",
            ),
        ),
        migrations.CreateModel(
            name="PeliculaComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comentario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppBlog.comentario",
                    ),
                ),
                (
                    "pelicula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppBlog.pelicula",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pelicula",
            name="comentarios",
            field=models.ManyToManyField(
                related_name="pelicula_comentarios",
                through="AppBlog.PeliculaComentario",
                to="AppBlog.comentario",
            ),
        ),
    ]
