# Generated by Django 4.1.7 on 2023-03-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0002_alter_comentario_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="puntacion",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
