# Generated by Django 4.1.7 on 2023-03-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0004_puntuacion"),
    ]

    operations = [
        migrations.RemoveField(model_name="pelicula", name="puntacion",),
    ]
