# Generated by Django 4.1.7 on 2023-03-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0006_peliculaapi"),
    ]

    operations = [
        migrations.DeleteModel(name="PeliculaAPI",),
    ]
